@Host= https://ads-pw-crud-livraria-back-end.herokuapp.com

#@Host = http://localhost:8080

###
#Requisição  GET para listar todos 

GET {{Host}}


###
#Requisição GET para listar detalhes de 1 registro 

GET {{Host}}/detalhes/1


###
#Requisição POST para cadastrar um novo livro

POST {{Host}}/adicionar
Content-Type: application/json

{
    "titulo": "A",
    "autor": "B",
    "tipo": "C",
    "resumo": "D" 
}


###
#Requisição POST para editar um livro
POST {{Host}}/adicionar
Content-Type: application/json

{
    "id": 1,
    "titulo": "E",
    "autor": "B",
    "tipo": "C",
    "resumo": "D"
}

###
#Requisição GET para deletar um livro

GET {{Host}}/deletar/1


